/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import da.Cola;
import da.ListaInsertion;
import da.ListaMerge;
import javax.swing.JOptionPane;
import sun.reflect.annotation.TypeAnnotationParser;

/**
 *
 * @author Ricardo Rodriguez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        this.setLocationRelativeTo(this);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMergeCola = new javax.swing.JButton();
        btnInsertionCir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnMerge1 = new javax.swing.JButton();
        btnInsertionSim = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1305, 536));
        setResizable(false);
        setSize(new java.awt.Dimension(1305, 536));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Principal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Metodos de ordenamiento:");

        btnMergeCola.setBackground(new java.awt.Color(102, 102, 102));
        btnMergeCola.setText("Merge Sort Cola");
        btnMergeCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeColaActionPerformed(evt);
            }
        });

        btnInsertionCir.setBackground(new java.awt.Color(102, 102, 102));
        btnInsertionCir.setText("Insertion Sort Lista Circular");
        btnInsertionCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertionCirActionPerformed(evt);
            }
        });

        jLabel3.setText("Elija el metodo que desea realizar");

        txtDuracion.setEditable(false);
        txtDuracion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setText("Duración:");

        btnHistorial.setBackground(new java.awt.Color(102, 102, 102));
        btnHistorial.setText("Historial");

        btnModulo.setBackground(new java.awt.Color(102, 102, 102));
        btnModulo.setText("Modulo Grafico");
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });

        btnMerge1.setBackground(new java.awt.Color(102, 102, 102));
        btnMerge1.setText("Merge Sort Lista Simple");
        btnMerge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerge1ActionPerformed(evt);
            }
        });

        btnInsertionSim.setBackground(new java.awt.Color(102, 102, 102));
        btnInsertionSim.setText("Insertion Sort Lista Simple");
        btnInsertionSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertionSimActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMergeCola, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInsertionSim, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInsertionCir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMerge1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMerge1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMergeCola, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertionSim, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertionCir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        
        ModuloGrafico mg = new ModuloGrafico();
        
        this.setVisible(false);
        mg.setVisible(true);
        
    }//GEN-LAST:event_btnModuloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
         System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMerge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerge1ActionPerformed
        
        double tiempoInicioLS = System.nanoTime();
        ListaMerge simpleM = new ListaMerge();
        
        simpleM.add("Ricardo", "Rodriguez", "Moya", "2-0740-0314", 22.0);
        simpleM.add("Juan", "Perez", "Mora", "1-1121-0507", 29.0);
        simpleM.add("Brayan", "Oconer", "Splinner", "M12378", 34.0);
        simpleM.add("Obama", "Barack", "Simion", "E78072", 56.0);
        simpleM.mergeSort(simpleM.getCabeza());
        simpleM.pasaportePrimero();
        
        double tiempoTotalLS = System.nanoTime() - tiempoInicioLS;
        
        String tiempo = String.valueOf(tiempoTotalLS/1000000);
        
        txtDuracion.setText(tiempo + "s");
        
//        JOptionPane.showMessageDialog(this, "Se ejecuto el MergeSort Simple.");
        
    }//GEN-LAST:event_btnMerge1ActionPerformed

    private void btnMergeColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeColaActionPerformed
        
        double tiempoInicioLS = System.nanoTime();
        Cola cola = new Cola();
        
        cola.queue("Santiago", "Mora", "Valverde", "7-0740-0314", 6.0);
        cola.queue("Jose", "Carballo", "Flores", "1-1354-0621", 18.0);
        cola.queue("Alexander", "Ramirez", "Varela", "1-1224-0247", 55.0);
        cola.queue("Jeylin", "Smith", "Jones", "M12378", 24.0);
        cola.mergeSort(cola.top());
        cola.pasaportePrimero();
        
        double tiempoTotalLS = System.nanoTime() - tiempoInicioLS;
        
        String tiempo = String.valueOf(tiempoTotalLS/1000000);
        
        txtDuracion.setText(tiempo + "s");
        
    }//GEN-LAST:event_btnMergeColaActionPerformed

    private void btnInsertionSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertionSimActionPerformed
        
        double tiempoInicioLS = System.nanoTime();
        ListaInsertion simpleIn = new ListaInsertion();
        
        simpleIn.add("Javier", "Moya", "Prendas", "4-0621-0115", 12.0);
        simpleIn.add("Xinia", "Portugues", "Aviles", "2-1354-0621", 46.0);
        simpleIn.add("Julio", "Ramirez", "Ventega", "2-1224-0247", 40.0);
        simpleIn.add("Jhonson", "Williams", "Fallen", "R73950", 86.0);
        simpleIn.insertionSort();
        
        double tiempoTotalLS = System.nanoTime() - tiempoInicioLS;
        
        String tiempo = String.valueOf(tiempoTotalLS/1000000);
        
        txtDuracion.setText(tiempo + "s");
    }//GEN-LAST:event_btnInsertionSimActionPerformed

    private void btnInsertionCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertionCirActionPerformed
        
        double tiempoInicioLS = System.nanoTime();
        ListaInsertion circularIn = new ListaInsertion();
        
        circularIn.addCircular("David", "Angulo", "Tivas", "9-0461-0872", 25.0);
        circularIn.addCircular("Heylin", "Rodriguez", "Flores", "5-2454-0621", 19.0);
        circularIn.addCircular("Alexander", "Ramirez", "Varela", "6-2454-0247", 50.0);
        circularIn.addCircular("Williams", "Smith", "Tomatito", "E12658", 31.0);
         circularIn.insertionSortCircular();
        
        double tiempoTotalLS = System.nanoTime() - tiempoInicioLS;
        
        String tiempo = String.valueOf(tiempoTotalLS/1000000);
        
        txtDuracion.setText(tiempo + "s");
        
    }//GEN-LAST:event_btnInsertionCirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInsertionCir;
    private javax.swing.JButton btnInsertionSim;
    private javax.swing.JButton btnMerge1;
    private javax.swing.JButton btnMergeCola;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDuracion;
    // End of variables declaration//GEN-END:variables
}
